SYSTEM_NAME_HELP = "Ingrese el nombre del sistema o equipo asociado (p. ej. Iluminación, Sistema de Vapor, etc.)"
TRADEMARK_NAME = "Marca"
TRADEMARK_NAME_HELP = "Ingrese el nombre de la marca (p. ej. Grundfos, Spirax Sarco, etc.)"


MATERIAL_NAME_HELP = "ID único para este material particular en toda la biblioteca"
MATERIAL_DESCRIPTION = "Descripción"
MATERIAL_POSITION = "Posición"
MATERIAL_OWNER = "Propietario"
MATERIAL_OWNER_HELP = "Sector propietario del material"
MATERIAL_VALUE = "Valor (USD)"
MATERIAL_VALUE_HELP = "Valor neto USD"
MATERIAL_STOCK_NAME = "Stock"
MATERIAL_STOCK_HELP = "Cantidad existente en pañol"
MATERIAL_SAFETY_NAME = "Stock de seguridad"
MATERIAL_SAFETY_HELP = "Mínimo stock recomendado"
MATERIAL_SYSTEM_HELP = "Seleccione un sistema/equipo para este material"

MATERIAL_STATUS_AVAILABLE = "Disponible"
MATERIAL_STATUS_RESERVED = "Reservado"
MATERIAL_STATUS_HELP = "Disponibilidad del material"
