# Generated by Django 3.2.9 on 2022-02-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20220208_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'Disponible'), ('r', 'Reservado')], default='m', help_text='Disponibilidad del libro', max_length=1),
        ),
    ]
