# Generated by Django 3.2.9 on 2022-02-08 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_material_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='system',
        ),
        migrations.AddField(
            model_name='material',
            name='system',
            field=models.ForeignKey(help_text='Seleccione un sistema/equipo para este material', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.system'),
        ),
    ]
