# Generated by Django 3.2.9 on 2022-02-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20220208_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='last_entry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'Disponible'), ('r', 'Reservado')], default='d', help_text='Disponibilidad del material', max_length=1),
        ),
        migrations.AddField(
            model_name='material',
            name='value',
            field=models.IntegerField(blank=True, default=0, help_text='Valor neto USD', null=True, verbose_name='Valor (USD)'),
        ),
    ]
