# Generated by Django 3.2.9 on 2022-02-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20220208_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='owner',
            field=models.CharField(help_text='Sector propietario del material', max_length=20, null=True),
        ),
    ]
