# Generated by Django 3.2.9 on 2022-02-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_material_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
