# Generated by Django 3.2.9 on 2022-02-12 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_material_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('e', 'Entrada'), ('s', 'Salida')], max_length=1)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='material',
            name='owner',
            field=models.CharField(help_text='Sector propietario del material', max_length=20, null=True, verbose_name='Propietario'),
        ),
        migrations.AlterField(
            model_name='material',
            name='position',
            field=models.CharField(max_length=50, null=True, verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='name',
            field=models.CharField(help_text='Ingrese el nombre de la marca (p. ej. Grundfos, Spirax Sarco, etc.)', max_length=200, verbose_name='Marca'),
        ),
        migrations.DeleteModel(
            name='MaterialInstance',
        ),
        migrations.AddField(
            model_name='materialhistory',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.material'),
        ),
    ]
