# Generated by Django 3.2.9 on 2022-02-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_materialhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialhistory',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
